### ISSUE TITLE
They Took Down All the Sensors!

### ISSUE THREAD

**Issue by Nick-the-BinaryTree** [emilyeserven/stamfordhackathon2016#4]
This app has been temporarily incapacitated.

Any screenshots from before that time?

**Comment by emilyeserven** [comment]
I added a message noting that the app isn't pulling data in at the moment. Haven't posted a screenshot yet though, so I'm going to keep this issue open for now.

**Comment by Nick-the-BinaryTree** [comment]
Closing, as we have all grown old.
